---
version: 2
updates:
  # Enable version updates for pytest_otel
  - package-ecosystem: "pip"
    # Check for updates once a month
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"

  # Maintain dependencies for GitHub Actions (/.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "elastic/observablt-ci"
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
