---
version: 2
updates:

  # Maintain dependencies for GitHub Actions (/.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
