repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  - repo: https://github.com/elastic/apm-pipeline-library
    rev: current
    hooks:
      - id: check-bash-syntax
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args:
          [
            --strict,
            --show-error-codes,
            --no-warn-unused-ignores,
            --implicit-reexport,
          ]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: tests|conftest.py|setup.py
