# Config file for `updatecli compose ...`.
# https://www.updatecli.io/docs/core/compose/
policies:
  - name: Handle ecs-logging specs
    policy: ghcr.io/elastic/oblt-updatecli-policies/apm/ecs-logging-specs:0.5.0@sha256:fbe1697bb32f0d5222ce5267cb8ed9b8e079bf17bee06fb16b4e5c2c3351549e
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/ecs-logging-specs.yml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.9.1@sha256:5bbca67a9e31bf5432d5cae1452b9fc770014151ddd856f367ccb9ba46f6f8bb
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/update-compose.yml
